### ISSUE TITLE
An invalid RRule throws IllegalStateException too many empty recurrence sets

### ISSUE THREAD

**Issue by chungonn** [dmfs/lib-recur#121]
Is it valid for get an `java.lang.IllegalStateException: too many empty recurrence sets` for invoking the method `iterator` on an invalid RRule or should it just return null? Please see the sample Scala code below. 

At the moment, I am catching any IllegalStateException thrown while invoking the method `iterator` and return a null instead. Do I also need to check if the message is  `too many empty recurrence sets`?

I am using lib-recur version 0.1.5.0 

```scala
    val rrule = RecurrenceRule("FREQ=WEEKLY;INTERVAL=2;BYDAY=SA;BYHOUR=19;BYMINUTE=0;BYSECOND=0;BYSETPOS=2")
    val today = DateTime.parse("20210306")
    val iter = rrule.iterator(today)
```

```scala
java.lang.IllegalStateException: too many empty recurrence sets

	at org.dmfs.rfc5545.recur.BySetPosFilter.nextSet(BySetPosFilter.java:88)
	at org.dmfs.rfc5545.recur.BySetPosFilter.next(BySetPosFilter.java:69)
	at org.dmfs.rfc5545.recur.RecurrenceRuleIterator.fetchNextInstance(RecurrenceRuleIterator.java:95)
	at org.dmfs.rfc5545.recur.RecurrenceRuleIterator.<init>(RecurrenceRuleIterator.java:89)
	at org.dmfs.rfc5545.recur.RecurrenceRule.iterator(RecurrenceRule.java:2216)
	at org.dmfs.rfc5545.recur.RecurrenceSet2Suite.$init$$$anonfun$3(RecurrenceSet2Suite.scala:57)

```

**Comment by dmfs** [comment]
Yeah, it's a bit odd to get this when calling the `iterator` method. The Iterator tries to advance to the first occurrence (in order to know whether there *is* a next occurrence).

I didn't come up with a better solution yet. Ideally we would just return an empty iterator when the rule is empty. However, it's hard to determine whether the rule actually is empty. I think it might be possible to construct a rule that loops over several thousand instances before an actual occurrence is found. The exception is basically the circuit breaker that prevents an infinite loop for rules that don't yield a single occurrence.

In your case it might even be possible to determine that the rule is empty. I need to think about this, but my first instinct is that a `WEEKLY` rule is empty when the `BYSETPOS` value is larger than the product of the count of parameters of each `BY*` part. For your rule that would result in `1 * 1 * 1 * 1 < 2`. In fact this might work for all rules with a FREQ other than `YEARLY` and `MONTHLY`.

Catching the exception should be fine. Don't evaluate the message. It could change any time without further notice.

**Comment by chungonn** [comment]
Hi Marten,
Much appreciated for sharing your thoughts and a detailed explanation. I
already had a workaround by catching the IllegalStateExpection, the only
concern I have was there might be another same class of exception that I
should not catch hence I was thinking of evaluating the message for a
specific exception. Anyways, you helped address my concern and all is good
on my end. I just wrapped the Iterator within an option in my quote.

Thanks again for your help.
