### ISSUE TITLE
WEEKLY with INTERVAL finds unexpected first instance

### ISSUE THREAD

**Issue by chriskessel** [dmfs/lib-recur#141]
Using 0.17.1

I'm not sure if this is a bug or a misunderstanding, but if I do a rule like this:
`"FREQ=WEEKLY;INTERVAL=5;BYDAY=WE"`

Then what happens is if the start date is on or before Wednesday, then it finds the upcoming Wedneday that week as the initial date. So, if the date is 2024/10/1 (Tuesday) then it finds 10/2 as the starting date as expected.

However, if the starting date is 2024/10/3 (Thursday) then rather than start the following Wednesday (10/9) instead it finds 11/6 as the start date, which is 5 weeks (the INTERVAL) from 10/2, which seems odd because that's the day _before_ the starting date of 10/3. 

Here's a little test method that tries starting on each day of October 2024 for the RRULE mentioned above and spits out what the first instance date is.

```
    @Test
    public void testEvery5Weeks() throws InvalidRecurrenceRuleException {
        for (int day = 1; day < 30; day++) {
            final RecurrenceRule rule = new RecurrenceRule("FREQ=WEEKLY;INTERVAL=5;BYDAY=WE", RecurrenceRule.RfcMode.RFC5545_LAX);
            final LocalDate startDate = LocalDate.of(2024, 10, day);
            final RecurrenceRuleIterator iterator = rule.iterator(
                    ZonedDateTime.of(startDate, LocalTime.MIN, ZONE_ID_US_WEST).toInstant().toEpochMilli(),
                    TimeZone.getTimeZone(ZONE_ID_US_WEST));

            final ZonedDateTime next = ZonedDateTime.ofInstant(Instant.ofEpochMilli(iterator.nextMillis()), ZONE_ID_US_WEST);
            System.out.println(next.toLocalDate());
        }
    }
```

Which results in this output showing how, each week, it'll start on WE of that week if the date is on/before WE. Otherwise, it punts out 5 weeks from that week's WE.
```
2024-10-02
2024-10-02
2024-11-06
2024-11-06
2024-11-06
2024-11-06
2024-10-09
2024-10-09
2024-10-09
2024-11-13
2024-11-13
2024-11-13
2024-11-13
2024-10-16
2024-10-16
2024-10-16
2024-11-20
2024-11-20
2024-11-20
2024-11-20
2024-10-23
2024-10-23
2024-10-23
2024-11-27
2024-11-27
2024-11-27
2024-11-27
2024-10-30
2024-10-30
```

**Comment by dmfs** [comment]
Hmm, right. This isn't very intuitive. The problem is the "unsynchronized start date", i.e. a start date that doesn't match the rule. According to RFC 5545, the occurrences of such an event are "undefined". The current behavior is easily explained: the rule iterator considers the week of the start date to be the first week, even if no instance in that week is iterated (due to the unsynchronized start) and the next instance occurs 5 weeks after the start week.

If you'd combine this with the iterator that always emits the start instance, even if not synchronized, you'd expect the next instance to be 5 weeks in the future and that behavior is kept even if the start instance is not emitted.

I'm not sure if it's even possible to solve this in a way that works for everyone. I guess that's why the spec took the easy way out and declared it "undefined". I wonder how other implementations handle this case. Unless there is a critical mass of other implementations that treats this case differently, I'd probably keep it like it is.

If you just use this to iterate dates and you don't care about interoperability with other implementations, you could set the start of the week to the weekday of your actual start. This should ensure it always emits the very next instance that matches the rule.

I.e. `FREQ=WEEKLY;WKST=TH;INTERVAL=5;BYDAY=WE` with a start date on a Thursday should emit the next Wednesday as the first instance, not the one five week in the future. That's because Thursday is now considered the first day of the week and the next Wednesday is still in the same week.

**Comment by chriskessel** [comment]
Thanks, I appreciate the insight. I'll figure out something on our side to do a better job of specifying a start date that synchronizes with a weekday (or day of month in the MONTHLY case as I'd guess that's has the same issue).
